version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6392:6379"

  vector_retrieval_service:
    build:
      context: ../..
      dockerfile: services/vector_retrieval_service/Dockerfile
    command:
      [
        "uvicorn",
        "services.vector_retrieval_service.main_app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "9412",
      ]
    ports:
      - "9412:9412"
    environment:
      - VECTOR_RETRIEVAL_SERVICE_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9112:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - vector_retrieval_service
