apiVersion: v1
kind: Service
metadata:
  name: pgbackrest-backup
  labels:
    app: pgbackrest-backup
spec:
  selector:
    app: pgbackrest-backup
  ports:
    - name: http
      port: 9544
      targetPort: 9544
  type: ClusterIP
