apiVersion: v1
kind: Service
metadata:
  name: open-source-license
  labels:
    app: open-source-license
spec:
  selector:
    app: open-source-license
  ports:
    - name: http
      port: 9555
      targetPort: 9555
  type: ClusterIP
