version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6391:6379"

  cache_service:
    build:
      context: ../..
      dockerfile: services/cache_service/Dockerfile
    command:
      [
        "uvicorn",
        "services.cache_service.main_app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "9411",
      ]
    ports:
      - "9411:9411"
    environment:
      - CACHE_SERVICE_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9111:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cache_service
