apiVersion: v1
kind: Service
metadata:
  name: qdrant-shard
  labels:
    app: qdrant-shard
spec:
  selector:
    app: qdrant-shard
  ports:
    - name: http
      port: 9503
      targetPort: 9503
  type: ClusterIP
