apiVersion: v1
kind: Service
metadata:
  name: service-mesh
  labels:
    app: service-mesh
spec:
  selector:
    app: service-mesh
  ports:
    - name: http
      port: 9520
      targetPort: 9520
  type: ClusterIP
