apiVersion: v1
kind: Service
metadata:
  name: rag-service
  labels:
    app: rag-service
spec:
  selector:
    app: rag-service
  ports:
    - name: http
      port: 9406
      targetPort: 9406
  type: ClusterIP
