apiVersion: v1
kind: Service
metadata:
  name: database-optimization
  labels:
    app: database-optimization
spec:
  selector:
    app: database-optimization
  ports:
    - name: http
      port: 9562
      targetPort: 9562
  type: ClusterIP
