# -*- coding: utf-8 -*-
"""Real TestClient tests for api/alert_router.py with no mocks.

Note: every /api/v1/alerts/* path is whitelisted as public in the global
RBAC middleware, so auth is not the choke point for these endpoints.  We still
use real JWT admin headers (generated by core.auth_service) where a token is
convenient for exercising the request state.
"""

import asyncio  # noqa: F401  # Imported for test setup

import pytest  # noqa: F401  # Imported for test setup
from fastapi import FastAPI
from fastapi.testclient import TestClient

import api.alert_router
from core.alert_engine import alert_history
from core.alert_intelligence import AlertPattern, alert_intelligence_engine
from core.alert_service import alert_service
from core.auth_service import create_access_token
from core.metrics_history import metrics_history
from core.query_optimization import query_cache
from main import app


@pytest.fixture(scope="module")
def app_client(ensure_database):
    with TestClient(app) as client:
        yield client


@pytest.fixture(scope="module")
def admin_headers():
    token = create_access_token({"sub": "admin", "role": "admin"})
    return {"Authorization": f"Bearer {token}"}


@pytest.fixture(autouse=True)
def reset_state():
    alert_history.clear()
    metrics_history.clear()
    query_cache.invalidate()
    yield
    alert_history.clear()
    metrics_history.clear()
    query_cache.invalidate()


def _create_alert(**kwargs):
    defaults = {
        "severity": "warning",
        "message": "test alert",
        "source": "pytest",
    }
    defaults.update(kwargs)
    return asyncio.run(alert_service.create_alert(**defaults))


def test_get_alerts_empty(app_client):
    resp = app_client.get("/api/v1/alerts/")
    assert resp.status_code == 200
    data = resp.json()
    assert data["total"] == 0
    assert data["alerts"] == []


def test_create_and_list_alerts(app_client):
    _create_alert(severity="critical", message="first")
    _create_alert(severity="warning", message="second")
    resp = app_client.get("/api/v1/alerts/", params={"limit": 1})
    assert resp.status_code == 200
    data = resp.json()
    assert data["total"] == 2
    assert len(data["alerts"]) == 1
    assert data["alerts"][0]["message"] == "second"


def test_get_alerts_limit_validation(app_client):
    assert app_client.get("/api/v1/alerts/", params={"limit": 0}).status_code == 422
    assert app_client.get("/api/v1/alerts/", params={"limit": 501}).status_code == 422
    assert app_client.get("/api/v1/alerts/", params={"limit": -1}).status_code == 422


def test_acknowledge_alert(app_client, admin_headers):
    alert = _create_alert(severity="critical", message="ack me")
    resp = app_client.post(
        f"/api/v1/alerts/{alert['id']}/acknowledge",
        headers=admin_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["status"] == "acknowledged"

    listed = app_client.get("/api/v1/alerts/", params={"limit": 5}).json()
    assert listed["alerts"][0]["status"] == "acknowledged"


def test_resolve_alert(app_client, admin_headers):
    alert = _create_alert(severity="high", message="resolve me")
    resp = app_client.post(
        f"/api/v1/alerts/{alert['id']}/resolve",
        headers=admin_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["status"] == "resolved"

    listed = app_client.get("/api/v1/alerts/", params={"limit": 5}).json()
    assert listed["alerts"][0]["status"] == "resolved"


def test_acknowledge_unknown_id(app_client, admin_headers):
    resp = app_client.post(
        "/api/v1/alerts/00000000-0000-0000-0000-000000000000/acknowledge",
        headers=admin_headers,
    )
    assert resp.status_code == 200
    assert resp.json()["status"] == "acknowledged"


def test_clear_alerts_admin(app_client, admin_headers):
    _create_alert(severity="warning", message="to clear")
    _create_alert(severity="critical", message="to clear 2")
    resp = app_client.delete("/api/v1/alerts/", headers=admin_headers)
    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "ok"
    assert data["deleted_count"] >= 2

    listed = app_client.get("/api/v1/alerts/").json()
    assert listed["total"] == 0


def test_clear_alerts_unknown_client_ip():
    """Covers request.client being None in clear_alerts_endpoint."""
    small_app = FastAPI()
    small_app.include_router(api.alert_router.router)
    with TestClient(small_app, client=None) as client:
        _create_alert(severity="warning", message="x")
        resp = client.delete("/api/v1/alerts/")
        assert resp.status_code == 200
        assert resp.json()["status"] == "ok"
        assert resp.json()["operator_ip"] == "unknown"


def test_404_unknown_alert_path(app_client, admin_headers):
    assert app_client.get("/api/v1/alerts/999", headers=admin_headers).status_code == 404


def test_get_intelligence_statistics(app_client, admin_headers):
    resp = app_client.get("/api/v1/alerts/intelligence/statistics", headers=admin_headers)
    assert resp.status_code == 200
    data = resp.json()
    assert "total_patterns" in data


def test_get_alert_patterns(app_client, admin_headers):
    from datetime import datetime

    alert_intelligence_engine.patterns["p1"] = AlertPattern(
        pattern_id="p1",
        signature="cpu_high",
        frequency=5,
        last_seen=datetime.now(),
        is_noise=False,
        noise_reason="",
    )
    alert_intelligence_engine.patterns["p2"] = AlertPattern(
        pattern_id="p2",
        signature="mem_noise",
        frequency=10,
        last_seen=datetime.now(),
        is_noise=True,
        noise_reason="frequent",
    )

    resp = app_client.get(
        "/api/v1/alerts/intelligence/patterns",
        params={"limit": 10, "include_noise": False},
        headers=admin_headers,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["total"] == 1
    assert all(not p["is_noise"] for p in data["patterns"])

    resp = app_client.get(
        "/api/v1/alerts/intelligence/patterns",
        params={"limit": 10, "include_noise": True},
        headers=admin_headers,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["total"] == 2


def test_add_routing_rule(app_client, admin_headers):
    resp = app_client.post(
        "/api/v1/alerts/intelligence/routing-rules",
        headers=admin_headers,
        json={
            "conditions": {"level": "critical"},
            "destination": "immediate",
            "description": "critical alerts",
            "priority": 1,
            "extra_field_ignored": 123,
        },
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "success"
    assert data["rule"]["destination"] == "immediate"

    assert (
        app_client.post(
            "/api/v1/alerts/intelligence/routing-rules",
            headers=admin_headers,
            json={"conditions": {}},
        ).status_code
        == 422
    )


def test_add_suppression_rule(app_client, admin_headers):
    resp = app_client.post(
        "/api/v1/alerts/intelligence/suppression-rules",
        headers=admin_headers,
        json={
            "pattern": "cpu_normal",
            "reason": "normal fluctuation",
            "suppression_window": 120,
            "enabled": False,
        },
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "success"
    assert data["rule"]["enabled"] is False

    assert (
        app_client.post(
            "/api/v1/alerts/intelligence/suppression-rules",
            headers=admin_headers,
            json={"pattern": "only-pattern"},
        ).status_code
        == 422
    )


def _push_cpu_points(count):
    for i in range(count):
        metrics_history.push(
            cpu=float(20 + i),
            memory=float(50),
            net_in=float(1.0),
            timestamp=f"12:{i % 60:02d}:00",
        )


def test_predict_alert_trend_success(app_client, admin_headers):
    metrics_history.clear()
    _push_cpu_points(11)
    resp = app_client.post(
        "/api/v1/alerts/intelligence/predict",
        headers=admin_headers,
        json={"metric_name": "cpu", "horizon_hours": 3},
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["metric_name"] == "cpu"
    assert len(data["predicted_values"]) == 3
    assert data["model_used"] == "rule_based"


def test_predict_alert_trend_missing_metric(app_client, admin_headers):
    metrics_history.clear()
    _push_cpu_points(11)
    resp = app_client.post(
        "/api/v1/alerts/intelligence/predict",
        headers=admin_headers,
        json={"metric_name": "does_not_exist", "horizon_hours": 3},
    )
    assert resp.status_code == 400


def test_predict_alert_trend_insufficient_data(app_client, admin_headers):
    metrics_history.clear()
    _push_cpu_points(5)
    resp = app_client.post(
        "/api/v1/alerts/intelligence/predict",
        headers=admin_headers,
        json={"metric_name": "cpu", "horizon_hours": 3},
    )
    assert resp.status_code == 400


def test_predict_alert_trend_invalid_timestamp(app_client, admin_headers):
    metrics_history.clear()
    _push_cpu_points(11)
    metrics_history.timestamps.append("not-a-time")
    metrics_history.cpu.append(999.0)
    resp = app_client.post(
        "/api/v1/alerts/intelligence/predict",
        headers=admin_headers,
        json={"metric_name": "cpu", "horizon_hours": 3},
    )
    assert resp.status_code == 200


def test_get_topology_context(app_client, admin_headers):
    alert_history.appendleft(
        {
            "id": "t1",
            "host": "db1",
            "category": "database",
            "level": "critical",
            "title": "db down",
        }
    )
    alert_history.appendleft(
        {
            "id": "t2",
            "host": "web1",
            "category": "system",
            "level": "warning",
            "title": "slow",
        }
    )
    resp = app_client.get("/api/v1/alerts/intelligence/topology", headers=admin_headers)
    assert resp.status_code == 200
    data = resp.json()
    assert "nodes" in data
    assert "edges" in data


def test_route_alerts_intelligently(app_client, admin_headers):
    alert_history.clear()
    alert_history.appendleft(
        {
            "id": "r1",
            "host": "db1",
            "category": "database",
            "level": "critical",
            "title": "db down",
        }
    )
    alert_history.appendleft(
        {
            "id": "r2",
            "host": "fw1",
            "category": "security",
            "level": "high",
            "title": "attack",
        }
    )
    resp = app_client.post("/api/v1/alerts/intelligence/route-alerts", headers=admin_headers)
    assert resp.status_code == 200
    data = resp.json()
    assert data["total_alerts"] == 2
    assert "routes" in data


def test_intelligence_unavailable_503(app_client, admin_headers):
    original = api.alert_router.ALERT_INTELLIGENCE_AVAILABLE
    try:
        api.alert_router.ALERT_INTELLIGENCE_AVAILABLE = False
        endpoints = [
            ("GET", "/api/v1/alerts/intelligence/statistics", None),
            ("GET", "/api/v1/alerts/intelligence/patterns", {"include_noise": True}),
            (
                "POST",
                "/api/v1/alerts/intelligence/predict",
                {"metric_name": "cpu", "horizon_hours": 3},
            ),
            ("GET", "/api/v1/alerts/intelligence/topology", None),
            (
                "POST",
                "/api/v1/alerts/intelligence/routing-rules",
                {
                    "conditions": {"level": "critical"},
                    "destination": "immediate",
                },
            ),
            (
                "POST",
                "/api/v1/alerts/intelligence/suppression-rules",
                {
                    "pattern": "x",
                    "reason": "y",
                },
            ),
            ("POST", "/api/v1/alerts/intelligence/route-alerts", None),
        ]
        for method, path, body in endpoints:
            if method == "GET":
                resp = app_client.get(path, headers=admin_headers, params=body or {})
            else:
                resp = app_client.post(path, headers=admin_headers, json=body or {})
            assert resp.status_code == 503, f"{method} {path} expected 503, got {resp.status_code}"
    finally:
        api.alert_router.ALERT_INTELLIGENCE_AVAILABLE = original

    # Sanity: after restoring, the engine is reachable again.
    assert (
        app_client.get("/api/v1/alerts/intelligence/statistics", headers=admin_headers).status_code
        == 200
    )
