apiVersion: v1
kind: Service
metadata:
  name: plugin-system
  labels:
    app: plugin-system
spec:
  selector:
    app: plugin-system
  ports:
    - name: http
      port: 9556
      targetPort: 9556
  type: ClusterIP
