apiVersion: v1
kind: Service
metadata:
  name: chaos-mesh
  labels:
    app: chaos-mesh
spec:
  selector:
    app: chaos-mesh
  ports:
    - name: http
      port: 9546
      targetPort: 9546
  type: ClusterIP
