apiVersion: v1
kind: Service
metadata:
  name: alert-rule
  labels:
    app: alert-rule
spec:
  selector:
    app: alert-rule
  ports:
    - name: http
      port: 9522
      targetPort: 9522
  type: ClusterIP
