apiVersion: v1
kind: Service
metadata:
  name: cloud-monitoring
  labels:
    app: cloud-monitoring
spec:
  selector:
    app: cloud-monitoring
  ports:
    - name: http
      port: 9534
      targetPort: 9534
  type: ClusterIP
