# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from extensions.addons.ai_plus.environment_management_service.grpc import environment_management_pb2 as environment__management__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in environment_management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnvironmentManagementServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/CreateEnvironment',
                request_serializer=environment__management__pb2.CreateEnvironmentRequest.SerializeToString,
                response_deserializer=environment__management__pb2.EnvironmentResponse.FromString,
                _registered_method=True)
        self.GetEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetEnvironment',
                request_serializer=environment__management__pb2.GetEnvironmentRequest.SerializeToString,
                response_deserializer=environment__management__pb2.EnvironmentResponse.FromString,
                _registered_method=True)
        self.ListEnvironments = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/ListEnvironments',
                request_serializer=environment__management__pb2.ListEnvironmentsRequest.SerializeToString,
                response_deserializer=environment__management__pb2.ListEnvironmentsResponse.FromString,
                _registered_method=True)
        self.UpdateEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/UpdateEnvironment',
                request_serializer=environment__management__pb2.UpdateEnvironmentRequest.SerializeToString,
                response_deserializer=environment__management__pb2.EnvironmentResponse.FromString,
                _registered_method=True)
        self.DeleteEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/DeleteEnvironment',
                request_serializer=environment__management__pb2.DeleteEnvironmentRequest.SerializeToString,
                response_deserializer=environment__management__pb2.DeleteEnvironmentResponse.FromString,
                _registered_method=True)
        self.SyncConfig = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/SyncConfig',
                request_serializer=environment__management__pb2.SyncConfigRequest.SerializeToString,
                response_deserializer=environment__management__pb2.SyncConfigResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetConfig',
                request_serializer=environment__management__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=environment__management__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/UpdateConfig',
                request_serializer=environment__management__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=environment__management__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.DeployToEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/DeployToEnvironment',
                request_serializer=environment__management__pb2.DeployRequest.SerializeToString,
                response_deserializer=environment__management__pb2.DeployResponse.FromString,
                _registered_method=True)
        self.GetDeploymentStatus = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetDeploymentStatus',
                request_serializer=environment__management__pb2.GetDeploymentStatusRequest.SerializeToString,
                response_deserializer=environment__management__pb2.DeploymentStatusResponse.FromString,
                _registered_method=True)
        self.RollbackDeployment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/RollbackDeployment',
                request_serializer=environment__management__pb2.RollbackRequest.SerializeToString,
                response_deserializer=environment__management__pb2.RollbackResponse.FromString,
                _registered_method=True)
        self.SetEnvironmentVariable = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/SetEnvironmentVariable',
                request_serializer=environment__management__pb2.SetVariableRequest.SerializeToString,
                response_deserializer=environment__management__pb2.VariableResponse.FromString,
                _registered_method=True)
        self.GetEnvironmentVariable = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetEnvironmentVariable',
                request_serializer=environment__management__pb2.GetVariableRequest.SerializeToString,
                response_deserializer=environment__management__pb2.VariableResponse.FromString,
                _registered_method=True)
        self.ListEnvironmentVariables = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/ListEnvironmentVariables',
                request_serializer=environment__management__pb2.ListVariablesRequest.SerializeToString,
                response_deserializer=environment__management__pb2.ListVariablesResponse.FromString,
                _registered_method=True)
        self.DeleteEnvironmentVariable = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/DeleteEnvironmentVariable',
                request_serializer=environment__management__pb2.DeleteVariableRequest.SerializeToString,
                response_deserializer=environment__management__pb2.DeleteVariableResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/HealthCheck',
                request_serializer=environment__management__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=environment__management__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetEnvironmentMetrics = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetEnvironmentMetrics',
                request_serializer=environment__management__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=environment__management__pb2.MetricsResponse.FromString,
                _registered_method=True)


class EnvironmentManagementServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateEnvironment(self, request, context):
        """Environment management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEnvironments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncConfig(self, request, context):
        """Configuration management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployToEnvironment(self, request, context):
        """Deployment orchestration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEnvironmentVariable(self, request, context):
        """Environment variable management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvironmentVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEnvironmentVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEnvironmentVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvironmentMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvironment,
                    request_deserializer=environment__management__pb2.CreateEnvironmentRequest.FromString,
                    response_serializer=environment__management__pb2.EnvironmentResponse.SerializeToString,
            ),
            'GetEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironment,
                    request_deserializer=environment__management__pb2.GetEnvironmentRequest.FromString,
                    response_serializer=environment__management__pb2.EnvironmentResponse.SerializeToString,
            ),
            'ListEnvironments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvironments,
                    request_deserializer=environment__management__pb2.ListEnvironmentsRequest.FromString,
                    response_serializer=environment__management__pb2.ListEnvironmentsResponse.SerializeToString,
            ),
            'UpdateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEnvironment,
                    request_deserializer=environment__management__pb2.UpdateEnvironmentRequest.FromString,
                    response_serializer=environment__management__pb2.EnvironmentResponse.SerializeToString,
            ),
            'DeleteEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnvironment,
                    request_deserializer=environment__management__pb2.DeleteEnvironmentRequest.FromString,
                    response_serializer=environment__management__pb2.DeleteEnvironmentResponse.SerializeToString,
            ),
            'SyncConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncConfig,
                    request_deserializer=environment__management__pb2.SyncConfigRequest.FromString,
                    response_serializer=environment__management__pb2.SyncConfigResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=environment__management__pb2.GetConfigRequest.FromString,
                    response_serializer=environment__management__pb2.ConfigResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=environment__management__pb2.UpdateConfigRequest.FromString,
                    response_serializer=environment__management__pb2.ConfigResponse.SerializeToString,
            ),
            'DeployToEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployToEnvironment,
                    request_deserializer=environment__management__pb2.DeployRequest.FromString,
                    response_serializer=environment__management__pb2.DeployResponse.SerializeToString,
            ),
            'GetDeploymentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentStatus,
                    request_deserializer=environment__management__pb2.GetDeploymentStatusRequest.FromString,
                    response_serializer=environment__management__pb2.DeploymentStatusResponse.SerializeToString,
            ),
            'RollbackDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackDeployment,
                    request_deserializer=environment__management__pb2.RollbackRequest.FromString,
                    response_serializer=environment__management__pb2.RollbackResponse.SerializeToString,
            ),
            'SetEnvironmentVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEnvironmentVariable,
                    request_deserializer=environment__management__pb2.SetVariableRequest.FromString,
                    response_serializer=environment__management__pb2.VariableResponse.SerializeToString,
            ),
            'GetEnvironmentVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironmentVariable,
                    request_deserializer=environment__management__pb2.GetVariableRequest.FromString,
                    response_serializer=environment__management__pb2.VariableResponse.SerializeToString,
            ),
            'ListEnvironmentVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvironmentVariables,
                    request_deserializer=environment__management__pb2.ListVariablesRequest.FromString,
                    response_serializer=environment__management__pb2.ListVariablesResponse.SerializeToString,
            ),
            'DeleteEnvironmentVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnvironmentVariable,
                    request_deserializer=environment__management__pb2.DeleteVariableRequest.FromString,
                    response_serializer=environment__management__pb2.DeleteVariableResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=environment__management__pb2.HealthCheckRequest.FromString,
                    response_serializer=environment__management__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetEnvironmentMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironmentMetrics,
                    request_deserializer=environment__management__pb2.GetMetricsRequest.FromString,
                    response_serializer=environment__management__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'environment_management.EnvironmentManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('environment_management.EnvironmentManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvironmentManagementService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/CreateEnvironment',
            environment__management__pb2.CreateEnvironmentRequest.SerializeToString,
            environment__management__pb2.EnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/GetEnvironment',
            environment__management__pb2.GetEnvironmentRequest.SerializeToString,
            environment__management__pb2.EnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEnvironments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/ListEnvironments',
            environment__management__pb2.ListEnvironmentsRequest.SerializeToString,
            environment__management__pb2.ListEnvironmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/UpdateEnvironment',
            environment__management__pb2.UpdateEnvironmentRequest.SerializeToString,
            environment__management__pb2.EnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/DeleteEnvironment',
            environment__management__pb2.DeleteEnvironmentRequest.SerializeToString,
            environment__management__pb2.DeleteEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/SyncConfig',
            environment__management__pb2.SyncConfigRequest.SerializeToString,
            environment__management__pb2.SyncConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/GetConfig',
            environment__management__pb2.GetConfigRequest.SerializeToString,
            environment__management__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/UpdateConfig',
            environment__management__pb2.UpdateConfigRequest.SerializeToString,
            environment__management__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployToEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/DeployToEnvironment',
            environment__management__pb2.DeployRequest.SerializeToString,
            environment__management__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeploymentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/GetDeploymentStatus',
            environment__management__pb2.GetDeploymentStatusRequest.SerializeToString,
            environment__management__pb2.DeploymentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/RollbackDeployment',
            environment__management__pb2.RollbackRequest.SerializeToString,
            environment__management__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEnvironmentVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/SetEnvironmentVariable',
            environment__management__pb2.SetVariableRequest.SerializeToString,
            environment__management__pb2.VariableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvironmentVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/GetEnvironmentVariable',
            environment__management__pb2.GetVariableRequest.SerializeToString,
            environment__management__pb2.VariableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEnvironmentVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/ListEnvironmentVariables',
            environment__management__pb2.ListVariablesRequest.SerializeToString,
            environment__management__pb2.ListVariablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEnvironmentVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/DeleteEnvironmentVariable',
            environment__management__pb2.DeleteVariableRequest.SerializeToString,
            environment__management__pb2.DeleteVariableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/HealthCheck',
            environment__management__pb2.HealthCheckRequest.SerializeToString,
            environment__management__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvironmentMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/environment_management.EnvironmentManagementService/GetEnvironmentMetrics',
            environment__management__pb2.GetMetricsRequest.SerializeToString,
            environment__management__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
