# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from extensions.addons.ai_plus.environment_management_service.grpc import environment_management_pb2 as environment__management__pb2


class EnvironmentManagementServiceStub:
    """Missing associated documentation comment in .proto file."""
    
    def __init__(self, channel):
        """Constructor.
        
        Args:
            channel: A grpc.Channel.
        """
        self.CreateEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/CreateEnvironment',
                request_serializer=environment__management__pb2.CreateEnvironmentRequest.SerializeToString,
                response_deserializer=environment__management__pb2.EnvironmentResponse.FromString,
                )
        self.GetEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetEnvironment',
                request_serializer=environment__management__pb2.GetEnvironmentRequest.SerializeToString,
                response_deserializer=environment__management__pb2.EnvironmentResponse.FromString,
                )
        self.ListEnvironments = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/ListEnvironments',
                request_serializer=environment__management__pb2.ListEnvironmentsRequest.SerializeToString,
                response_deserializer=environment__management__pb2.ListEnvironmentsResponse.FromString,
                )
        self.UpdateEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/UpdateEnvironment',
                request_serializer=environment__management__pb2.UpdateEnvironmentRequest.SerializeToString,
                response_deserializer=environment__management__pb2.EnvironmentResponse.FromString,
                )
        self.DeleteEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/DeleteEnvironment',
                request_serializer=environment__management__pb2.DeleteEnvironmentRequest.SerializeToString,
                response_deserializer=environment__management__pb2.DeleteEnvironmentResponse.FromString,
                )
        self.SyncConfig = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/SyncConfig',
                request_serializer=environment__management__pb2.SyncConfigRequest.SerializeToString,
                response_deserializer=environment__management__pb2.SyncConfigResponse.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetConfig',
                request_serializer=environment__management__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=environment__management__pb2.ConfigResponse.FromString,
                )
        self.UpdateConfig = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/UpdateConfig',
                request_serializer=environment__management__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=environment__management__pb2.ConfigResponse.FromString,
                )
        self.DeployToEnvironment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/DeployToEnvironment',
                request_serializer=environment__management__pb2.DeployRequest.SerializeToString,
                response_deserializer=environment__management__pb2.DeployResponse.FromString,
                )
        self.GetDeploymentStatus = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetDeploymentStatus',
                request_serializer=environment__management__pb2.GetDeploymentStatusRequest.SerializeToString,
                response_deserializer=environment__management__pb2.DeploymentStatusResponse.FromString,
                )
        self.RollbackDeployment = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/RollbackDeployment',
                request_serializer=environment__management__pb2.RollbackRequest.SerializeToString,
                response_deserializer=environment__management__pb2.RollbackResponse.FromString,
                )
        self.SetEnvironmentVariable = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/SetEnvironmentVariable',
                request_serializer=environment__management__pb2.SetVariableRequest.SerializeToString,
                response_deserializer=environment__management__pb2.VariableResponse.FromString,
                )
        self.GetEnvironmentVariable = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetEnvironmentVariable',
                request_serializer=environment__management__pb2.GetVariableRequest.SerializeToString,
                response_deserializer=environment__management__pb2.VariableResponse.FromString,
                )
        self.ListEnvironmentVariables = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/ListEnvironmentVariables',
                request_serializer=environment__management__pb2.ListVariablesRequest.SerializeToString,
                response_deserializer=environment__management__pb2.ListVariablesResponse.FromString,
                )
        self.DeleteEnvironmentVariable = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/DeleteEnvironmentVariable',
                request_serializer=environment__management__pb2.DeleteVariableRequest.SerializeToString,
                response_deserializer=environment__management__pb2.DeleteVariableResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/HealthCheck',
                request_serializer=environment__management__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=environment__management__pb2.HealthCheckResponse.FromString,
                )
        self.GetEnvironmentMetrics = channel.unary_unary(
                '/environment_management.EnvironmentManagementService/GetEnvironmentMetrics',
                request_serializer=environment__management__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=environment__management__pb2.MetricsResponse.FromString,
                )


class EnvironmentManagementServiceServicer:
    """Missing associated documentation comment in .proto file."""
    
    def CreateEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def GetEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def ListEnvironments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def UpdateEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def DeleteEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def SyncConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def DeployToEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def GetDeploymentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def RollbackDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def SetEnvironmentVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def GetEnvironmentVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def ListEnvironmentVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def DeleteEnvironmentVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    def GetEnvironmentMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvironment,
                    request_deserializer=environment__management__pb2.CreateEnvironmentRequest.FromString,
                    response_serializer=environment__management__pb2.EnvironmentResponse.SerializeToString,
            ),
            'GetEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironment,
                    request_deserializer=environment__management__pb2.GetEnvironmentRequest.FromString,
                    response_serializer=environment__management__pb2.EnvironmentResponse.SerializeToString,
            ),
            'ListEnvironments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvironments,
                    request_deserializer=environment__management__pb2.ListEnvironmentsRequest.FromString,
                    response_serializer=environment__management__pb2.ListEnvironmentsResponse.SerializeToString,
            ),
            'UpdateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEnvironment,
                    request_deserializer=environment__management__pb2.UpdateEnvironmentRequest.FromString,
                    response_serializer=environment__management__pb2.EnvironmentResponse.SerializeToString,
            ),
            'DeleteEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnvironment,
                    request_deserializer=environment__management__pb2.DeleteEnvironmentRequest.FromString,
                    response_serializer=environment__management__pb2.DeleteEnvironmentResponse.SerializeToString,
            ),
            'SyncConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncConfig,
                    request_deserializer=environment__management__pb2.SyncConfigRequest.FromString,
                    response_serializer=environment__management__pb2.SyncConfigResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=environment__management__pb2.GetConfigRequest.FromString,
                    response_serializer=environment__management__pb2.ConfigResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=environment__management__pb2.UpdateConfigRequest.FromString,
                    response_serializer=environment__management__pb2.ConfigResponse.SerializeToString,
            ),
            'DeployToEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployToEnvironment,
                    request_deserializer=environment__management__pb2.DeployRequest.FromString,
                    response_serializer=environment__management__pb2.DeployResponse.SerializeToString,
            ),
            'GetDeploymentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentStatus,
                    request_deserializer=environment__management__pb2.GetDeploymentStatusRequest.FromString,
                    response_serializer=environment__management__pb2.DeploymentStatusResponse.SerializeToString,
            ),
            'RollbackDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackDeployment,
                    request_deserializer=environment__management__pb2.RollbackRequest.FromString,
                    response_serializer=environment__management__pb2.RollbackResponse.SerializeToString,
            ),
            'SetEnvironmentVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEnvironmentVariable,
                    request_deserializer=environment__management__pb2.SetVariableRequest.FromString,
                    response_serializer=environment__management__pb2.VariableResponse.SerializeToString,
            ),
            'GetEnvironmentVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironmentVariable,
                    request_deserializer=environment__management__pb2.GetVariableRequest.FromString,
                    response_serializer=environment__management__pb2.VariableResponse.SerializeToString,
            ),
            'ListEnvironmentVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvironmentVariables,
                    request_deserializer=environment__management__pb2.ListVariablesRequest.FromString,
                    response_serializer=environment__management__pb2.ListVariablesResponse.SerializeToString,
            ),
            'DeleteEnvironmentVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnvironmentVariable,
                    request_deserializer=environment__management__pb2.DeleteVariableRequest.FromString,
                    response_serializer=environment__management__pb2.DeleteVariableResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=environment__management__pb2.HealthCheckRequest.FromString,
                    response_serializer=environment__management__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetEnvironmentMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironmentMetrics,
                    request_deserializer=environment__management__pb2.GetMetricsRequest.FromString,
                    response_serializer=environment__management__pb2.MetricsResponse.SerializeToString,
            ),
    }
    server.add_generic_rpc_handlers((grpc.method_handlers_generic_handler(
            'environment_management.EnvironmentManagementService', rpc_method_handlers),))
