# -*- coding: utf-8 -*-
"""Unified configuration management compatibility module.

The legacy implementation has been moved to ``core/config_manager.py`` and
``core/config_models.py``.  This module re-exports the public API so existing
imports (``core.environment_config``, ``core.config_validation``, tests, etc.)
continue to work.
"""

from core.config_manager import (
    ConfigFormat,
    ConfigLoader,
    ConfigManager,
    ConfigSource,
    ConfigValidator,
    config_manager,
    get_config_value,
    load_config,
    save_config,
    setup_unified_configuration,
)
from core.config_models import (
    AIConfig,
    AISettings,
    AppConfig,
    AppSettings,
    CacheConfig,
    CacheSettings,
    CorsConfig,
    CorsSettings,
    DatabaseConfig,
    DatabaseSettings,
    Environment,
    FeatureFlags,
    IntegrationConfig,
    IntegrationSettings,
    L2AnalysisConfig,
    L2AnalysisSettings,
    L3ProcessingConfig,
    L3ProcessingSettings,
    L5InterfaceConfig,
    L5InterfaceSettings,
    L6ExecutionConfig,
    L6ExecutionSettings,
    L7IntegrationConfig,
    L7IntegrationSettings,
    LoggingConfig,
    LoggingSettings,
    MonitoringConfig,
    MonitoringSettings,
    OpenTelemetryConfig,
    OpenTelemetrySettings,
    RateLimitConfig,
    RateLimitSettings,
    RedisConfig,
    RedisSettings,
    SecurityConfig,
    SecuritySettings,
    ServiceWorkerConfig,
    ServiceWorkerSettings,
    Settings,
    SlackConfig,
    SlackSettings,
    StorageConfig,
    StorageSettings,
    TeamsConfig,
    TeamsSettings,
    UnifiedConfig,
)

__all__ = [
    "Environment",
    "DatabaseConfig",
    "RedisConfig",
    "SecurityConfig",
    "MonitoringConfig",
    "AIConfig",
    "CorsConfig",
    "CacheConfig",
    "RateLimitConfig",
    "LoggingConfig",
    "OpenTelemetryConfig",
    "SlackConfig",
    "TeamsConfig",
    "IntegrationConfig",
    "FeatureFlags",
    "StorageConfig",
    "L2AnalysisConfig",
    "L3ProcessingConfig",
    "L5InterfaceConfig",
    "L6ExecutionConfig",
    "L7IntegrationConfig",
    "ServiceWorkerConfig",
    "DatabaseSettings",
    "RedisSettings",
    "SecuritySettings",
    "MonitoringSettings",
    "AISettings",
    "CorsSettings",
    "CacheSettings",
    "RateLimitSettings",
    "LoggingSettings",
    "OpenTelemetrySettings",
    "SlackSettings",
    "TeamsSettings",
    "IntegrationSettings",
    "StorageSettings",
    "L2AnalysisSettings",
    "L3ProcessingSettings",
    "L5InterfaceSettings",
    "L6ExecutionSettings",
    "L7IntegrationSettings",
    "ServiceWorkerSettings",
    "AppConfig",
    "AppSettings",
    "UnifiedConfig",
    "Settings",
    "ConfigManager",
    "ConfigLoader",
    "ConfigValidator",
    "ConfigFormat",
    "ConfigSource",
    "load_config",
    "save_config",
    "get_config_value",
    "setup_unified_configuration",
    "config_manager",
]
