apiVersion: v1
kind: Service
metadata:
  name: postgresql-shard
  labels:
    app: postgresql-shard
spec:
  selector:
    app: postgresql-shard
  ports:
    - name: http
      port: 9501
      targetPort: 9501
  type: ClusterIP
