apiVersion: v1
kind: Service
metadata:
  name: distributed-tracing
  labels:
    app: distributed-tracing
spec:
  selector:
    app: distributed-tracing
  ports:
    - name: http
      port: 9569
      targetPort: 9569
  type: ClusterIP
