apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-audit
  labels:
    app: elasticsearch-audit
spec:
  selector:
    app: elasticsearch-audit
  ports:
    - name: http
      port: 9542
      targetPort: 9542
  type: ClusterIP
