apiVersion: v1
kind: Service
metadata:
  name: automated-ops
  labels:
    app: automated-ops
spec:
  selector:
    app: automated-ops
  ports:
    - name: http
      port: 9566
      targetPort: 9566
  type: ClusterIP
