apiVersion: v1
kind: Service
metadata:
  name: kafka-event
  labels:
    app: kafka-event
spec:
  selector:
    app: kafka-event
  ports:
    - name: http
      port: 9525
      targetPort: 9525
  type: ClusterIP
