apiVersion: v1
kind: Service
metadata:
  name: incident-response
  labels:
    app: incident-response
spec:
  selector:
    app: incident-response
  ports:
    - name: http
      port: 9553
      targetPort: 9553
  type: ClusterIP
