apiVersion: v1
kind: Service
metadata:
  name: log-aggregation
  labels:
    app: log-aggregation
spec:
  selector:
    app: log-aggregation
  ports:
    - name: http
      port: 9567
      targetPort: 9567
  type: ClusterIP
