apiVersion: v1
kind: Service
metadata:
  name: sphinx-documentation
  labels:
    app: sphinx-documentation
spec:
  selector:
    app: sphinx-documentation
  ports:
    - name: http
      port: 9550
      targetPort: 9550
  type: ClusterIP
