# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import access_control_pb2 as proto_dot_access__control__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/access_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccessControlServiceStub:
    """Access Control Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePermission = channel.unary_unary(
                '/access_control.AccessControlService/CreatePermission',
                request_serializer=proto_dot_access__control__pb2.CreatePermissionRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.PermissionResponse.FromString,
                _registered_method=True)
        self.UpdatePermission = channel.unary_unary(
                '/access_control.AccessControlService/UpdatePermission',
                request_serializer=proto_dot_access__control__pb2.UpdatePermissionRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.PermissionResponse.FromString,
                _registered_method=True)
        self.DeletePermission = channel.unary_unary(
                '/access_control.AccessControlService/DeletePermission',
                request_serializer=proto_dot_access__control__pb2.DeletePermissionRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetPermission = channel.unary_unary(
                '/access_control.AccessControlService/GetPermission',
                request_serializer=proto_dot_access__control__pb2.GetPermissionRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.PermissionResponse.FromString,
                _registered_method=True)
        self.ListPermissions = channel.unary_unary(
                '/access_control.AccessControlService/ListPermissions',
                request_serializer=proto_dot_access__control__pb2.ListPermissionsRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.PermissionsResponse.FromString,
                _registered_method=True)
        self.CreateRole = channel.unary_unary(
                '/access_control.AccessControlService/CreateRole',
                request_serializer=proto_dot_access__control__pb2.CreateRoleRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.RoleResponse.FromString,
                _registered_method=True)
        self.UpdateRole = channel.unary_unary(
                '/access_control.AccessControlService/UpdateRole',
                request_serializer=proto_dot_access__control__pb2.UpdateRoleRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.RoleResponse.FromString,
                _registered_method=True)
        self.DeleteRole = channel.unary_unary(
                '/access_control.AccessControlService/DeleteRole',
                request_serializer=proto_dot_access__control__pb2.DeleteRoleRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetRole = channel.unary_unary(
                '/access_control.AccessControlService/GetRole',
                request_serializer=proto_dot_access__control__pb2.GetRoleRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.RoleResponse.FromString,
                _registered_method=True)
        self.ListRoles = channel.unary_unary(
                '/access_control.AccessControlService/ListRoles',
                request_serializer=proto_dot_access__control__pb2.ListRolesRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.RolesResponse.FromString,
                _registered_method=True)
        self.AssignRole = channel.unary_unary(
                '/access_control.AccessControlService/AssignRole',
                request_serializer=proto_dot_access__control__pb2.AssignRoleRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RevokeRole = channel.unary_unary(
                '/access_control.AccessControlService/RevokeRole',
                request_serializer=proto_dot_access__control__pb2.RevokeRoleRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetSubjectRoles = channel.unary_unary(
                '/access_control.AccessControlService/GetSubjectRoles',
                request_serializer=proto_dot_access__control__pb2.GetSubjectRolesRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.SubjectRolesResponse.FromString,
                _registered_method=True)
        self.CreatePolicy = channel.unary_unary(
                '/access_control.AccessControlService/CreatePolicy',
                request_serializer=proto_dot_access__control__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.PolicyResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/access_control.AccessControlService/UpdatePolicy',
                request_serializer=proto_dot_access__control__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.PolicyResponse.FromString,
                _registered_method=True)
        self.DeletePolicy = channel.unary_unary(
                '/access_control.AccessControlService/DeletePolicy',
                request_serializer=proto_dot_access__control__pb2.DeletePolicyRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/access_control.AccessControlService/GetPolicy',
                request_serializer=proto_dot_access__control__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.PolicyResponse.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/access_control.AccessControlService/ListPolicies',
                request_serializer=proto_dot_access__control__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.PoliciesResponse.FromString,
                _registered_method=True)
        self.CheckPermission = channel.unary_unary(
                '/access_control.AccessControlService/CheckPermission',
                request_serializer=proto_dot_access__control__pb2.CheckPermissionRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.CheckPermissionResponse.FromString,
                _registered_method=True)
        self.GetAuditLogs = channel.unary_unary(
                '/access_control.AccessControlService/GetAuditLogs',
                request_serializer=proto_dot_access__control__pb2.GetAuditLogsRequest.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.AuditLogsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/access_control.AccessControlService/HealthCheck',
                request_serializer=proto_dot_access__control__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_access__control__pb2.StatusResponse.FromString,
                _registered_method=True)


class AccessControlServiceServicer:
    """Access Control Service
    """

    def CreatePermission(self, request, context):
        """Permission management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRole(self, request, context):
        """Role management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubjectRoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicy(self, request, context):
        """Policy management (ABAC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPermission(self, request, context):
        """Access control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditLogs(self, request, context):
        """Audit logging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePermission,
                    request_deserializer=proto_dot_access__control__pb2.CreatePermissionRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.PermissionResponse.SerializeToString,
            ),
            'UpdatePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePermission,
                    request_deserializer=proto_dot_access__control__pb2.UpdatePermissionRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.PermissionResponse.SerializeToString,
            ),
            'DeletePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePermission,
                    request_deserializer=proto_dot_access__control__pb2.DeletePermissionRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.StatusResponse.SerializeToString,
            ),
            'GetPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPermission,
                    request_deserializer=proto_dot_access__control__pb2.GetPermissionRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.PermissionResponse.SerializeToString,
            ),
            'ListPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPermissions,
                    request_deserializer=proto_dot_access__control__pb2.ListPermissionsRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.PermissionsResponse.SerializeToString,
            ),
            'CreateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRole,
                    request_deserializer=proto_dot_access__control__pb2.CreateRoleRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.RoleResponse.SerializeToString,
            ),
            'UpdateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRole,
                    request_deserializer=proto_dot_access__control__pb2.UpdateRoleRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.RoleResponse.SerializeToString,
            ),
            'DeleteRole': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRole,
                    request_deserializer=proto_dot_access__control__pb2.DeleteRoleRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.StatusResponse.SerializeToString,
            ),
            'GetRole': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRole,
                    request_deserializer=proto_dot_access__control__pb2.GetRoleRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.RoleResponse.SerializeToString,
            ),
            'ListRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoles,
                    request_deserializer=proto_dot_access__control__pb2.ListRolesRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.RolesResponse.SerializeToString,
            ),
            'AssignRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRole,
                    request_deserializer=proto_dot_access__control__pb2.AssignRoleRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.StatusResponse.SerializeToString,
            ),
            'RevokeRole': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeRole,
                    request_deserializer=proto_dot_access__control__pb2.RevokeRoleRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.StatusResponse.SerializeToString,
            ),
            'GetSubjectRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubjectRoles,
                    request_deserializer=proto_dot_access__control__pb2.GetSubjectRolesRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.SubjectRolesResponse.SerializeToString,
            ),
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=proto_dot_access__control__pb2.CreatePolicyRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.PolicyResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=proto_dot_access__control__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.PolicyResponse.SerializeToString,
            ),
            'DeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicy,
                    request_deserializer=proto_dot_access__control__pb2.DeletePolicyRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.StatusResponse.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=proto_dot_access__control__pb2.GetPolicyRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.PolicyResponse.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=proto_dot_access__control__pb2.ListPoliciesRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.PoliciesResponse.SerializeToString,
            ),
            'CheckPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPermission,
                    request_deserializer=proto_dot_access__control__pb2.CheckPermissionRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.CheckPermissionResponse.SerializeToString,
            ),
            'GetAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditLogs,
                    request_deserializer=proto_dot_access__control__pb2.GetAuditLogsRequest.FromString,
                    response_serializer=proto_dot_access__control__pb2.AuditLogsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_access__control__pb2.Empty.FromString,
                    response_serializer=proto_dot_access__control__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'access_control.AccessControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('access_control.AccessControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccessControlService:
    """Access Control Service
    """

    @staticmethod
    def CreatePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/CreatePermission',
            proto_dot_access__control__pb2.CreatePermissionRequest.SerializeToString,
            proto_dot_access__control__pb2.PermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/UpdatePermission',
            proto_dot_access__control__pb2.UpdatePermissionRequest.SerializeToString,
            proto_dot_access__control__pb2.PermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/DeletePermission',
            proto_dot_access__control__pb2.DeletePermissionRequest.SerializeToString,
            proto_dot_access__control__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/GetPermission',
            proto_dot_access__control__pb2.GetPermissionRequest.SerializeToString,
            proto_dot_access__control__pb2.PermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/ListPermissions',
            proto_dot_access__control__pb2.ListPermissionsRequest.SerializeToString,
            proto_dot_access__control__pb2.PermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/CreateRole',
            proto_dot_access__control__pb2.CreateRoleRequest.SerializeToString,
            proto_dot_access__control__pb2.RoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/UpdateRole',
            proto_dot_access__control__pb2.UpdateRoleRequest.SerializeToString,
            proto_dot_access__control__pb2.RoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/DeleteRole',
            proto_dot_access__control__pb2.DeleteRoleRequest.SerializeToString,
            proto_dot_access__control__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/GetRole',
            proto_dot_access__control__pb2.GetRoleRequest.SerializeToString,
            proto_dot_access__control__pb2.RoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/ListRoles',
            proto_dot_access__control__pb2.ListRolesRequest.SerializeToString,
            proto_dot_access__control__pb2.RolesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/AssignRole',
            proto_dot_access__control__pb2.AssignRoleRequest.SerializeToString,
            proto_dot_access__control__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/RevokeRole',
            proto_dot_access__control__pb2.RevokeRoleRequest.SerializeToString,
            proto_dot_access__control__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubjectRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/GetSubjectRoles',
            proto_dot_access__control__pb2.GetSubjectRolesRequest.SerializeToString,
            proto_dot_access__control__pb2.SubjectRolesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/CreatePolicy',
            proto_dot_access__control__pb2.CreatePolicyRequest.SerializeToString,
            proto_dot_access__control__pb2.PolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/UpdatePolicy',
            proto_dot_access__control__pb2.UpdatePolicyRequest.SerializeToString,
            proto_dot_access__control__pb2.PolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/DeletePolicy',
            proto_dot_access__control__pb2.DeletePolicyRequest.SerializeToString,
            proto_dot_access__control__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/GetPolicy',
            proto_dot_access__control__pb2.GetPolicyRequest.SerializeToString,
            proto_dot_access__control__pb2.PolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/ListPolicies',
            proto_dot_access__control__pb2.ListPoliciesRequest.SerializeToString,
            proto_dot_access__control__pb2.PoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/CheckPermission',
            proto_dot_access__control__pb2.CheckPermissionRequest.SerializeToString,
            proto_dot_access__control__pb2.CheckPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/GetAuditLogs',
            proto_dot_access__control__pb2.GetAuditLogsRequest.SerializeToString,
            proto_dot_access__control__pb2.AuditLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/access_control.AccessControlService/HealthCheck',
            proto_dot_access__control__pb2.Empty.SerializeToString,
            proto_dot_access__control__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
