# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import aiops_pb2 as proto_dot_aiops__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/aiops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIOpsServiceStub:
    """AIOps Agent Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetrics = channel.unary_unary(
                '/aiops.AIOpsService/GetMetrics',
                request_serializer=proto_dot_aiops__pb2.MetricsRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.GetAlert = channel.unary_unary(
                '/aiops.AIOpsService/GetAlert',
                request_serializer=proto_dot_aiops__pb2.AlertRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.AlertResponse.FromString,
                _registered_method=True)
        self.ListAlerts = channel.unary_unary(
                '/aiops.AIOpsService/ListAlerts',
                request_serializer=proto_dot_aiops__pb2.AlertRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.AlertsResponse.FromString,
                _registered_method=True)
        self.CreateAlert = channel.unary_unary(
                '/aiops.AIOpsService/CreateAlert',
                request_serializer=proto_dot_aiops__pb2.CreateAlertRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.AlertResponse.FromString,
                _registered_method=True)
        self.ResolveAlert = channel.unary_unary(
                '/aiops.AIOpsService/ResolveAlert',
                request_serializer=proto_dot_aiops__pb2.ResolveAlertRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.Empty.FromString,
                _registered_method=True)
        self.GetTopProcesses = channel.unary_unary(
                '/aiops.AIOpsService/GetTopProcesses',
                request_serializer=proto_dot_aiops__pb2.ProcessRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.ProcessResponse.FromString,
                _registered_method=True)
        self.ExecuteRepair = channel.unary_unary(
                '/aiops.AIOpsService/ExecuteRepair',
                request_serializer=proto_dot_aiops__pb2.RepairRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.RepairResponse.FromString,
                _registered_method=True)
        self.ListRepairs = channel.unary_unary(
                '/aiops.AIOpsService/ListRepairs',
                request_serializer=proto_dot_aiops__pb2.RepairRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.RepairsResponse.FromString,
                _registered_method=True)
        self.Analyze = channel.unary_unary(
                '/aiops.AIOpsService/Analyze',
                request_serializer=proto_dot_aiops__pb2.AIAnalysisRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.AIAnalysisResponse.FromString,
                _registered_method=True)
        self.StreamMetrics = channel.unary_stream(
                '/aiops.AIOpsService/StreamMetrics',
                request_serializer=proto_dot_aiops__pb2.StreamRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.StreamAlerts = channel.unary_stream(
                '/aiops.AIOpsService/StreamAlerts',
                request_serializer=proto_dot_aiops__pb2.StreamRequest.SerializeToString,
                response_deserializer=proto_dot_aiops__pb2.StreamResponse.FromString,
                _registered_method=True)


class AIOpsServiceServicer:
    """AIOps Agent Service
    """

    def GetMetrics(self, request, context):
        """Metrics operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlert(self, request, context):
        """Alert operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopProcesses(self, request, context):
        """Process operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteRepair(self, request, context):
        """Repair operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRepairs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request, context):
        """AI operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMetrics(self, request, context):
        """Streaming operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIOpsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=proto_dot_aiops__pb2.MetricsRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.MetricsResponse.SerializeToString,
            ),
            'GetAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlert,
                    request_deserializer=proto_dot_aiops__pb2.AlertRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.AlertResponse.SerializeToString,
            ),
            'ListAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAlerts,
                    request_deserializer=proto_dot_aiops__pb2.AlertRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.AlertsResponse.SerializeToString,
            ),
            'CreateAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlert,
                    request_deserializer=proto_dot_aiops__pb2.CreateAlertRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.AlertResponse.SerializeToString,
            ),
            'ResolveAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveAlert,
                    request_deserializer=proto_dot_aiops__pb2.ResolveAlertRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.Empty.SerializeToString,
            ),
            'GetTopProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopProcesses,
                    request_deserializer=proto_dot_aiops__pb2.ProcessRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.ProcessResponse.SerializeToString,
            ),
            'ExecuteRepair': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteRepair,
                    request_deserializer=proto_dot_aiops__pb2.RepairRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.RepairResponse.SerializeToString,
            ),
            'ListRepairs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRepairs,
                    request_deserializer=proto_dot_aiops__pb2.RepairRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.RepairsResponse.SerializeToString,
            ),
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=proto_dot_aiops__pb2.AIAnalysisRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.AIAnalysisResponse.SerializeToString,
            ),
            'StreamMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=proto_dot_aiops__pb2.StreamRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.StreamResponse.SerializeToString,
            ),
            'StreamAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAlerts,
                    request_deserializer=proto_dot_aiops__pb2.StreamRequest.FromString,
                    response_serializer=proto_dot_aiops__pb2.StreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiops.AIOpsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiops.AIOpsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIOpsService:
    """AIOps Agent Service
    """

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.AIOpsService/GetMetrics',
            proto_dot_aiops__pb2.MetricsRequest.SerializeToString,
            proto_dot_aiops__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.AIOpsService/GetAlert',
            proto_dot_aiops__pb2.AlertRequest.SerializeToString,
            proto_dot_aiops__pb2.AlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.AIOpsService/ListAlerts',
            proto_dot_aiops__pb2.AlertRequest.SerializeToString,
            proto_dot_aiops__pb2.AlertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.AIOpsService/CreateAlert',
            proto_dot_aiops__pb2.CreateAlertRequest.SerializeToString,
            proto_dot_aiops__pb2.AlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.AIOpsService/ResolveAlert',
            proto_dot_aiops__pb2.ResolveAlertRequest.SerializeToString,
            proto_dot_aiops__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.AIOpsService/GetTopProcesses',
            proto_dot_aiops__pb2.ProcessRequest.SerializeToString,
            proto_dot_aiops__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteRepair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.AIOpsService/ExecuteRepair',
            proto_dot_aiops__pb2.RepairRequest.SerializeToString,
            proto_dot_aiops__pb2.RepairResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRepairs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.AIOpsService/ListRepairs',
            proto_dot_aiops__pb2.RepairRequest.SerializeToString,
            proto_dot_aiops__pb2.RepairsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.AIOpsService/Analyze',
            proto_dot_aiops__pb2.AIAnalysisRequest.SerializeToString,
            proto_dot_aiops__pb2.AIAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiops.AIOpsService/StreamMetrics',
            proto_dot_aiops__pb2.StreamRequest.SerializeToString,
            proto_dot_aiops__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiops.AIOpsService/StreamAlerts',
            proto_dot_aiops__pb2.StreamRequest.SerializeToString,
            proto_dot_aiops__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
