# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import automated_testing_pb2 as proto_dot_automated__testing__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/automated_testing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AutomatedTestingServiceStub:
    """Automated Testing Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTestSuite = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/CreateTestSuite',
                request_serializer=proto_dot_automated__testing__pb2.CreateTestSuiteRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.TestSuiteResponse.FromString,
                _registered_method=True)
        self.GetTestSuite = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/GetTestSuite',
                request_serializer=proto_dot_automated__testing__pb2.GetTestSuiteRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.TestSuiteResponse.FromString,
                _registered_method=True)
        self.ListTestSuites = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/ListTestSuites',
                request_serializer=proto_dot_automated__testing__pb2.ListTestSuitesRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.TestSuitesResponse.FromString,
                _registered_method=True)
        self.UpdateTestSuite = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/UpdateTestSuite',
                request_serializer=proto_dot_automated__testing__pb2.UpdateTestSuiteRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.TestSuiteResponse.FromString,
                _registered_method=True)
        self.DeleteTestSuite = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/DeleteTestSuite',
                request_serializer=proto_dot_automated__testing__pb2.DeleteTestSuiteRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.Empty.FromString,
                _registered_method=True)
        self.RunTests = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/RunTests',
                request_serializer=proto_dot_automated__testing__pb2.RunTestsRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.TestExecutionResponse.FromString,
                _registered_method=True)
        self.GetTestReport = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/GetTestReport',
                request_serializer=proto_dot_automated__testing__pb2.GetTestReportRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.TestReportResponse.FromString,
                _registered_method=True)
        self.ListTestReports = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/ListTestReports',
                request_serializer=proto_dot_automated__testing__pb2.ListTestReportsRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.TestReportsResponse.FromString,
                _registered_method=True)
        self.CreateSchedule = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/CreateSchedule',
                request_serializer=proto_dot_automated__testing__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.GetSchedule = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/GetSchedule',
                request_serializer=proto_dot_automated__testing__pb2.GetScheduleRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.ListSchedules = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/ListSchedules',
                request_serializer=proto_dot_automated__testing__pb2.ListSchedulesRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.SchedulesResponse.FromString,
                _registered_method=True)
        self.UpdateSchedule = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/UpdateSchedule',
                request_serializer=proto_dot_automated__testing__pb2.UpdateScheduleRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/DeleteSchedule',
                request_serializer=proto_dot_automated__testing__pb2.DeleteScheduleRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCoverage = channel.unary_unary(
                '/automated_testing.AutomatedTestingService/GetCoverage',
                request_serializer=proto_dot_automated__testing__pb2.GetCoverageRequest.SerializeToString,
                response_deserializer=proto_dot_automated__testing__pb2.TestCoverageResponse.FromString,
                _registered_method=True)


class AutomatedTestingServiceServicer:
    """Automated Testing Service
    """

    def CreateTestSuite(self, request, context):
        """Test suite operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestSuite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTestSuites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTestSuite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTestSuite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTests(self, request, context):
        """Test execution operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTestReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSchedule(self, request, context):
        """Schedule operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoverage(self, request, context):
        """Coverage operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutomatedTestingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTestSuite': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTestSuite,
                    request_deserializer=proto_dot_automated__testing__pb2.CreateTestSuiteRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.TestSuiteResponse.SerializeToString,
            ),
            'GetTestSuite': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestSuite,
                    request_deserializer=proto_dot_automated__testing__pb2.GetTestSuiteRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.TestSuiteResponse.SerializeToString,
            ),
            'ListTestSuites': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTestSuites,
                    request_deserializer=proto_dot_automated__testing__pb2.ListTestSuitesRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.TestSuitesResponse.SerializeToString,
            ),
            'UpdateTestSuite': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTestSuite,
                    request_deserializer=proto_dot_automated__testing__pb2.UpdateTestSuiteRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.TestSuiteResponse.SerializeToString,
            ),
            'DeleteTestSuite': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTestSuite,
                    request_deserializer=proto_dot_automated__testing__pb2.DeleteTestSuiteRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.Empty.SerializeToString,
            ),
            'RunTests': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTests,
                    request_deserializer=proto_dot_automated__testing__pb2.RunTestsRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.TestExecutionResponse.SerializeToString,
            ),
            'GetTestReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestReport,
                    request_deserializer=proto_dot_automated__testing__pb2.GetTestReportRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.TestReportResponse.SerializeToString,
            ),
            'ListTestReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTestReports,
                    request_deserializer=proto_dot_automated__testing__pb2.ListTestReportsRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.TestReportsResponse.SerializeToString,
            ),
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=proto_dot_automated__testing__pb2.CreateScheduleRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.ScheduleResponse.SerializeToString,
            ),
            'GetSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedule,
                    request_deserializer=proto_dot_automated__testing__pb2.GetScheduleRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.ScheduleResponse.SerializeToString,
            ),
            'ListSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=proto_dot_automated__testing__pb2.ListSchedulesRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.SchedulesResponse.SerializeToString,
            ),
            'UpdateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSchedule,
                    request_deserializer=proto_dot_automated__testing__pb2.UpdateScheduleRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.ScheduleResponse.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=proto_dot_automated__testing__pb2.DeleteScheduleRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.Empty.SerializeToString,
            ),
            'GetCoverage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoverage,
                    request_deserializer=proto_dot_automated__testing__pb2.GetCoverageRequest.FromString,
                    response_serializer=proto_dot_automated__testing__pb2.TestCoverageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automated_testing.AutomatedTestingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('automated_testing.AutomatedTestingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AutomatedTestingService:
    """Automated Testing Service
    """

    @staticmethod
    def CreateTestSuite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/CreateTestSuite',
            proto_dot_automated__testing__pb2.CreateTestSuiteRequest.SerializeToString,
            proto_dot_automated__testing__pb2.TestSuiteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestSuite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/GetTestSuite',
            proto_dot_automated__testing__pb2.GetTestSuiteRequest.SerializeToString,
            proto_dot_automated__testing__pb2.TestSuiteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTestSuites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/ListTestSuites',
            proto_dot_automated__testing__pb2.ListTestSuitesRequest.SerializeToString,
            proto_dot_automated__testing__pb2.TestSuitesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTestSuite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/UpdateTestSuite',
            proto_dot_automated__testing__pb2.UpdateTestSuiteRequest.SerializeToString,
            proto_dot_automated__testing__pb2.TestSuiteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTestSuite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/DeleteTestSuite',
            proto_dot_automated__testing__pb2.DeleteTestSuiteRequest.SerializeToString,
            proto_dot_automated__testing__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/RunTests',
            proto_dot_automated__testing__pb2.RunTestsRequest.SerializeToString,
            proto_dot_automated__testing__pb2.TestExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/GetTestReport',
            proto_dot_automated__testing__pb2.GetTestReportRequest.SerializeToString,
            proto_dot_automated__testing__pb2.TestReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTestReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/ListTestReports',
            proto_dot_automated__testing__pb2.ListTestReportsRequest.SerializeToString,
            proto_dot_automated__testing__pb2.TestReportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/CreateSchedule',
            proto_dot_automated__testing__pb2.CreateScheduleRequest.SerializeToString,
            proto_dot_automated__testing__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/GetSchedule',
            proto_dot_automated__testing__pb2.GetScheduleRequest.SerializeToString,
            proto_dot_automated__testing__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/ListSchedules',
            proto_dot_automated__testing__pb2.ListSchedulesRequest.SerializeToString,
            proto_dot_automated__testing__pb2.SchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/UpdateSchedule',
            proto_dot_automated__testing__pb2.UpdateScheduleRequest.SerializeToString,
            proto_dot_automated__testing__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/DeleteSchedule',
            proto_dot_automated__testing__pb2.DeleteScheduleRequest.SerializeToString,
            proto_dot_automated__testing__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automated_testing.AutomatedTestingService/GetCoverage',
            proto_dot_automated__testing__pb2.GetCoverageRequest.SerializeToString,
            proto_dot_automated__testing__pb2.TestCoverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
