# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import identity_management_pb2 as proto_dot_identity__management__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/identity_management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityManagementServiceStub:
    """Identity Management Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/identity_management.IdentityManagementService/CreateUser',
                request_serializer=proto_dot_identity__management__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/identity_management.IdentityManagementService/UpdateUser',
                request_serializer=proto_dot_identity__management__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.UserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/identity_management.IdentityManagementService/DeleteUser',
                request_serializer=proto_dot_identity__management__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/identity_management.IdentityManagementService/GetUser',
                request_serializer=proto_dot_identity__management__pb2.GetUserRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.UserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/identity_management.IdentityManagementService/ListUsers',
                request_serializer=proto_dot_identity__management__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.UsersResponse.FromString,
                _registered_method=True)
        self.SetUserAttribute = channel.unary_unary(
                '/identity_management.IdentityManagementService/SetUserAttribute',
                request_serializer=proto_dot_identity__management__pb2.SetUserAttributeRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteUserAttribute = channel.unary_unary(
                '/identity_management.IdentityManagementService/DeleteUserAttribute',
                request_serializer=proto_dot_identity__management__pb2.DeleteUserAttributeRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.EnableMFA = channel.unary_unary(
                '/identity_management.IdentityManagementService/EnableMFA',
                request_serializer=proto_dot_identity__management__pb2.EnableMFARequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.MFAConfigResponse.FromString,
                _registered_method=True)
        self.DisableMFA = channel.unary_unary(
                '/identity_management.IdentityManagementService/DisableMFA',
                request_serializer=proto_dot_identity__management__pb2.DisableMFARequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.VerifyMFA = channel.unary_unary(
                '/identity_management.IdentityManagementService/VerifyMFA',
                request_serializer=proto_dot_identity__management__pb2.VerifyMFARequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.MFAVerificationResponse.FromString,
                _registered_method=True)
        self.CreateUserGroup = channel.unary_unary(
                '/identity_management.IdentityManagementService/CreateUserGroup',
                request_serializer=proto_dot_identity__management__pb2.CreateUserGroupRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.UserGroupResponse.FromString,
                _registered_method=True)
        self.UpdateUserGroup = channel.unary_unary(
                '/identity_management.IdentityManagementService/UpdateUserGroup',
                request_serializer=proto_dot_identity__management__pb2.UpdateUserGroupRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.UserGroupResponse.FromString,
                _registered_method=True)
        self.DeleteUserGroup = channel.unary_unary(
                '/identity_management.IdentityManagementService/DeleteUserGroup',
                request_serializer=proto_dot_identity__management__pb2.DeleteUserGroupRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetUserGroup = channel.unary_unary(
                '/identity_management.IdentityManagementService/GetUserGroup',
                request_serializer=proto_dot_identity__management__pb2.GetUserGroupRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.UserGroupResponse.FromString,
                _registered_method=True)
        self.ListUserGroups = channel.unary_unary(
                '/identity_management.IdentityManagementService/ListUserGroups',
                request_serializer=proto_dot_identity__management__pb2.ListUserGroupsRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.UserGroupsResponse.FromString,
                _registered_method=True)
        self.AddUserToGroup = channel.unary_unary(
                '/identity_management.IdentityManagementService/AddUserToGroup',
                request_serializer=proto_dot_identity__management__pb2.AddUserToGroupRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RemoveUserFromGroup = channel.unary_unary(
                '/identity_management.IdentityManagementService/RemoveUserFromGroup',
                request_serializer=proto_dot_identity__management__pb2.RemoveUserFromGroupRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ConfigureSSO = channel.unary_unary(
                '/identity_management.IdentityManagementService/ConfigureSSO',
                request_serializer=proto_dot_identity__management__pb2.ConfigureSSORequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.SSOConfigResponse.FromString,
                _registered_method=True)
        self.SSOLogin = channel.unary_unary(
                '/identity_management.IdentityManagementService/SSOLogin',
                request_serializer=proto_dot_identity__management__pb2.SSOLoginRequest.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.SSOLoginResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/identity_management.IdentityManagementService/HealthCheck',
                request_serializer=proto_dot_identity__management__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_identity__management__pb2.StatusResponse.FromString,
                _registered_method=True)


class IdentityManagementServiceServicer:
    """Identity Management Service
    """

    def CreateUser(self, request, context):
        """User lifecycle management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserAttribute(self, request, context):
        """User attributes management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableMFA(self, request, context):
        """Multi-factor authentication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableMFA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyMFA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserGroup(self, request, context):
        """User group management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserToGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUserFromGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureSSO(self, request, context):
        """SSO integration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SSOLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=proto_dot_identity__management__pb2.CreateUserRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=proto_dot_identity__management__pb2.UpdateUserRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.UserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=proto_dot_identity__management__pb2.DeleteUserRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.StatusResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=proto_dot_identity__management__pb2.GetUserRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.UserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=proto_dot_identity__management__pb2.ListUsersRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.UsersResponse.SerializeToString,
            ),
            'SetUserAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserAttribute,
                    request_deserializer=proto_dot_identity__management__pb2.SetUserAttributeRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteUserAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserAttribute,
                    request_deserializer=proto_dot_identity__management__pb2.DeleteUserAttributeRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.StatusResponse.SerializeToString,
            ),
            'EnableMFA': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableMFA,
                    request_deserializer=proto_dot_identity__management__pb2.EnableMFARequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.MFAConfigResponse.SerializeToString,
            ),
            'DisableMFA': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableMFA,
                    request_deserializer=proto_dot_identity__management__pb2.DisableMFARequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.StatusResponse.SerializeToString,
            ),
            'VerifyMFA': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyMFA,
                    request_deserializer=proto_dot_identity__management__pb2.VerifyMFARequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.MFAVerificationResponse.SerializeToString,
            ),
            'CreateUserGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserGroup,
                    request_deserializer=proto_dot_identity__management__pb2.CreateUserGroupRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.UserGroupResponse.SerializeToString,
            ),
            'UpdateUserGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserGroup,
                    request_deserializer=proto_dot_identity__management__pb2.UpdateUserGroupRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.UserGroupResponse.SerializeToString,
            ),
            'DeleteUserGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserGroup,
                    request_deserializer=proto_dot_identity__management__pb2.DeleteUserGroupRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.StatusResponse.SerializeToString,
            ),
            'GetUserGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserGroup,
                    request_deserializer=proto_dot_identity__management__pb2.GetUserGroupRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.UserGroupResponse.SerializeToString,
            ),
            'ListUserGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserGroups,
                    request_deserializer=proto_dot_identity__management__pb2.ListUserGroupsRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.UserGroupsResponse.SerializeToString,
            ),
            'AddUserToGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserToGroup,
                    request_deserializer=proto_dot_identity__management__pb2.AddUserToGroupRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.StatusResponse.SerializeToString,
            ),
            'RemoveUserFromGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUserFromGroup,
                    request_deserializer=proto_dot_identity__management__pb2.RemoveUserFromGroupRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.StatusResponse.SerializeToString,
            ),
            'ConfigureSSO': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureSSO,
                    request_deserializer=proto_dot_identity__management__pb2.ConfigureSSORequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.SSOConfigResponse.SerializeToString,
            ),
            'SSOLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.SSOLogin,
                    request_deserializer=proto_dot_identity__management__pb2.SSOLoginRequest.FromString,
                    response_serializer=proto_dot_identity__management__pb2.SSOLoginResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_identity__management__pb2.Empty.FromString,
                    response_serializer=proto_dot_identity__management__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'identity_management.IdentityManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('identity_management.IdentityManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityManagementService:
    """Identity Management Service
    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/CreateUser',
            proto_dot_identity__management__pb2.CreateUserRequest.SerializeToString,
            proto_dot_identity__management__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/UpdateUser',
            proto_dot_identity__management__pb2.UpdateUserRequest.SerializeToString,
            proto_dot_identity__management__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/DeleteUser',
            proto_dot_identity__management__pb2.DeleteUserRequest.SerializeToString,
            proto_dot_identity__management__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/GetUser',
            proto_dot_identity__management__pb2.GetUserRequest.SerializeToString,
            proto_dot_identity__management__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/ListUsers',
            proto_dot_identity__management__pb2.ListUsersRequest.SerializeToString,
            proto_dot_identity__management__pb2.UsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetUserAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/SetUserAttribute',
            proto_dot_identity__management__pb2.SetUserAttributeRequest.SerializeToString,
            proto_dot_identity__management__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/DeleteUserAttribute',
            proto_dot_identity__management__pb2.DeleteUserAttributeRequest.SerializeToString,
            proto_dot_identity__management__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableMFA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/EnableMFA',
            proto_dot_identity__management__pb2.EnableMFARequest.SerializeToString,
            proto_dot_identity__management__pb2.MFAConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableMFA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/DisableMFA',
            proto_dot_identity__management__pb2.DisableMFARequest.SerializeToString,
            proto_dot_identity__management__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyMFA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/VerifyMFA',
            proto_dot_identity__management__pb2.VerifyMFARequest.SerializeToString,
            proto_dot_identity__management__pb2.MFAVerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUserGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/CreateUserGroup',
            proto_dot_identity__management__pb2.CreateUserGroupRequest.SerializeToString,
            proto_dot_identity__management__pb2.UserGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/UpdateUserGroup',
            proto_dot_identity__management__pb2.UpdateUserGroupRequest.SerializeToString,
            proto_dot_identity__management__pb2.UserGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/DeleteUserGroup',
            proto_dot_identity__management__pb2.DeleteUserGroupRequest.SerializeToString,
            proto_dot_identity__management__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/GetUserGroup',
            proto_dot_identity__management__pb2.GetUserGroupRequest.SerializeToString,
            proto_dot_identity__management__pb2.UserGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/ListUserGroups',
            proto_dot_identity__management__pb2.ListUserGroupsRequest.SerializeToString,
            proto_dot_identity__management__pb2.UserGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddUserToGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/AddUserToGroup',
            proto_dot_identity__management__pb2.AddUserToGroupRequest.SerializeToString,
            proto_dot_identity__management__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUserFromGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/RemoveUserFromGroup',
            proto_dot_identity__management__pb2.RemoveUserFromGroupRequest.SerializeToString,
            proto_dot_identity__management__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureSSO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/ConfigureSSO',
            proto_dot_identity__management__pb2.ConfigureSSORequest.SerializeToString,
            proto_dot_identity__management__pb2.SSOConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SSOLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/SSOLogin',
            proto_dot_identity__management__pb2.SSOLoginRequest.SerializeToString,
            proto_dot_identity__management__pb2.SSOLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity_management.IdentityManagementService/HealthCheck',
            proto_dot_identity__management__pb2.Empty.SerializeToString,
            proto_dot_identity__management__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
