# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import code_quality_pb2 as code__quality__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in code_quality_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodeQualityServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeCode = channel.unary_unary(
                '/code_quality.CodeQualityService/AnalyzeCode',
                request_serializer=code__quality__pb2.AnalyzeCodeRequest.SerializeToString,
                response_deserializer=code__quality__pb2.AnalyzeCodeResponse.FromString,
                _registered_method=True)
        self.CheckStyle = channel.unary_unary(
                '/code_quality.CodeQualityService/CheckStyle',
                request_serializer=code__quality__pb2.CheckStyleRequest.SerializeToString,
                response_deserializer=code__quality__pb2.CheckStyleResponse.FromString,
                _registered_method=True)
        self.CheckTypes = channel.unary_unary(
                '/code_quality.CodeQualityService/CheckTypes',
                request_serializer=code__quality__pb2.CheckTypesRequest.SerializeToString,
                response_deserializer=code__quality__pb2.CheckTypesResponse.FromString,
                _registered_method=True)
        self.CheckQuality = channel.unary_unary(
                '/code_quality.CodeQualityService/CheckQuality',
                request_serializer=code__quality__pb2.CheckQualityRequest.SerializeToString,
                response_deserializer=code__quality__pb2.CheckQualityResponse.FromString,
                _registered_method=True)
        self.SecurityCheck = channel.unary_unary(
                '/code_quality.CodeQualityService/SecurityCheck',
                request_serializer=code__quality__pb2.SecurityCheckRequest.SerializeToString,
                response_deserializer=code__quality__pb2.SecurityCheckResponse.FromString,
                _registered_method=True)
        self.AnalyzeComplexity = channel.unary_unary(
                '/code_quality.CodeQualityService/AnalyzeComplexity',
                request_serializer=code__quality__pb2.AnalyzeComplexityRequest.SerializeToString,
                response_deserializer=code__quality__pb2.AnalyzeComplexityResponse.FromString,
                _registered_method=True)
        self.DetectDuplication = channel.unary_unary(
                '/code_quality.CodeQualityService/DetectDuplication',
                request_serializer=code__quality__pb2.DetectDuplicationRequest.SerializeToString,
                response_deserializer=code__quality__pb2.DetectDuplicationResponse.FromString,
                _registered_method=True)
        self.CollectMetrics = channel.unary_unary(
                '/code_quality.CodeQualityService/CollectMetrics',
                request_serializer=code__quality__pb2.CollectMetricsRequest.SerializeToString,
                response_deserializer=code__quality__pb2.CollectMetricsResponse.FromString,
                _registered_method=True)


class CodeQualityServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeCode(self, request, context):
        """Analyze code quality
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStyle(self, request, context):
        """Check code style with flake8
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckTypes(self, request, context):
        """Check types with mypy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckQuality(self, request, context):
        """Check code quality with pylint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SecurityCheck(self, request, context):
        """Security check with bandit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeComplexity(self, request, context):
        """Analyze code complexity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectDuplication(self, request, context):
        """Detect code duplication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectMetrics(self, request, context):
        """Collect quality metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeQualityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeCode': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCode,
                    request_deserializer=code__quality__pb2.AnalyzeCodeRequest.FromString,
                    response_serializer=code__quality__pb2.AnalyzeCodeResponse.SerializeToString,
            ),
            'CheckStyle': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStyle,
                    request_deserializer=code__quality__pb2.CheckStyleRequest.FromString,
                    response_serializer=code__quality__pb2.CheckStyleResponse.SerializeToString,
            ),
            'CheckTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTypes,
                    request_deserializer=code__quality__pb2.CheckTypesRequest.FromString,
                    response_serializer=code__quality__pb2.CheckTypesResponse.SerializeToString,
            ),
            'CheckQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckQuality,
                    request_deserializer=code__quality__pb2.CheckQualityRequest.FromString,
                    response_serializer=code__quality__pb2.CheckQualityResponse.SerializeToString,
            ),
            'SecurityCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.SecurityCheck,
                    request_deserializer=code__quality__pb2.SecurityCheckRequest.FromString,
                    response_serializer=code__quality__pb2.SecurityCheckResponse.SerializeToString,
            ),
            'AnalyzeComplexity': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeComplexity,
                    request_deserializer=code__quality__pb2.AnalyzeComplexityRequest.FromString,
                    response_serializer=code__quality__pb2.AnalyzeComplexityResponse.SerializeToString,
            ),
            'DetectDuplication': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectDuplication,
                    request_deserializer=code__quality__pb2.DetectDuplicationRequest.FromString,
                    response_serializer=code__quality__pb2.DetectDuplicationResponse.SerializeToString,
            ),
            'CollectMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectMetrics,
                    request_deserializer=code__quality__pb2.CollectMetricsRequest.FromString,
                    response_serializer=code__quality__pb2.CollectMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'code_quality.CodeQualityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('code_quality.CodeQualityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeQualityService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/code_quality.CodeQualityService/AnalyzeCode',
            code__quality__pb2.AnalyzeCodeRequest.SerializeToString,
            code__quality__pb2.AnalyzeCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckStyle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/code_quality.CodeQualityService/CheckStyle',
            code__quality__pb2.CheckStyleRequest.SerializeToString,
            code__quality__pb2.CheckStyleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/code_quality.CodeQualityService/CheckTypes',
            code__quality__pb2.CheckTypesRequest.SerializeToString,
            code__quality__pb2.CheckTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/code_quality.CodeQualityService/CheckQuality',
            code__quality__pb2.CheckQualityRequest.SerializeToString,
            code__quality__pb2.CheckQualityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SecurityCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/code_quality.CodeQualityService/SecurityCheck',
            code__quality__pb2.SecurityCheckRequest.SerializeToString,
            code__quality__pb2.SecurityCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeComplexity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/code_quality.CodeQualityService/AnalyzeComplexity',
            code__quality__pb2.AnalyzeComplexityRequest.SerializeToString,
            code__quality__pb2.AnalyzeComplexityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectDuplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/code_quality.CodeQualityService/DetectDuplication',
            code__quality__pb2.DetectDuplicationRequest.SerializeToString,
            code__quality__pb2.DetectDuplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/code_quality.CodeQualityService/CollectMetrics',
            code__quality__pb2.CollectMetricsRequest.SerializeToString,
            code__quality__pb2.CollectMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
