apiVersion: v1
kind: Service
metadata:
  name: prometheus-integration
  labels:
    app: prometheus-integration
spec:
  selector:
    app: prometheus-integration
  ports:
    - name: http
      port: 9530
      targetPort: 9530
  type: ClusterIP
