apiVersion: v1
kind: Service
metadata:
  name: terraform-iac
  labels:
    app: terraform-iac
spec:
  selector:
    app: terraform-iac
  ports:
    - name: http
      port: 9536
      targetPort: 9536
  type: ClusterIP
