#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Baseline-based mypy gate.

``mypy.ini`` now covers the whole first-party tree (core/api/services/modules/
extensions/tests/scripts), which currently reports thousands of pre-existing
type errors (mostly SQLAlchemy 1.x-style ``Column`` declarations). Fixing them
all is a multi-week refactor, so this script makes the gate *honest and
regression-proof* instead of silently excluding whole layers:

* ``python scripts/mypy_baseline.py``           -> check against the baseline
* ``python scripts/mypy_baseline.py --update``  -> rewrite the baseline

A baseline entry is ``<path>|<error-code>|<message>`` — line/column numbers are
deliberately excluded so unrelated edits do not churn the file. The check fails
when a *new* error appears. Errors that disappeared are reported so the baseline
can be refreshed (that keeps the backlog shrinking rather than freezing).
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import List, Set

REPO_ROOT = Path(os.getenv("AIOPS_ROOT", Path(__file__).resolve().parents[1]))
BASELINE = REPO_ROOT / "mypy_baseline.txt"

# "path/to/file.py:12:5: error: message  [error-code]"
_ERROR_RE = re.compile(
    r"^(?P<path>[^:]+):\d+:\d+: (?P<level>error|note): (?P<message>.*?)(?:\s+\[(?P<code>[a-z-]+)\])?$"
)


def run_mypy() -> str:
    """Run mypy over the repository and return its combined output."""
    result = subprocess.run(
        [sys.executable, "-m", "mypy", ".", "--no-pretty"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )
    return result.stdout + result.stderr


def parse_errors(output: str) -> Set[str]:
    """Reduce mypy output to a set of location-independent error signatures."""
    entries: Set[str] = set()
    for raw in output.splitlines():
        match = _ERROR_RE.match(raw.strip())
        if not match or match.group("level") != "error":
            continue
        path = match.group("path").strip()
        if path.startswith(str(REPO_ROOT)):
            path = os.path.relpath(path, REPO_ROOT)
        code = match.group("code") or "no-code"
        message = re.sub(r"\s+", " ", match.group("message")).strip()
        # Drop the quoted identifiers that change with refactors but keep the gist.
        entries.add(f"{path}|{code}|{message}")
    return entries


def load_baseline() -> Set[str]:
    if not BASELINE.exists():
        return set()
    return {
        line.rstrip("\n")
        for line in BASELINE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    }


def write_baseline(entries: Set[str]) -> None:
    header = (
        "# mypy baseline — generated by scripts/mypy_baseline.py\n"
        "# Format: <path>|<error-code>|<message>\n"
        "# Checked by .github/workflows/quality_gates.yml. Refresh with:\n"
        "#   python scripts/mypy_baseline.py --update\n"
    )
    BASELINE.write_text(header + "\n".join(sorted(entries)) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true", help="Rewrite the baseline file.")
    parser.add_argument("--quiet", action="store_true", help="Only print the verdict.")
    args = parser.parse_args()

    print("Running mypy over the repository…")
    output = run_mypy()
    current = parse_errors(output)
    print(f"mypy reported {len(current)} distinct errors.")

    if args.update:
        write_baseline(current)
        print(f"Baseline written to {BASELINE.relative_to(REPO_ROOT)} ({len(current)} entries).")
        return 0

    baseline = load_baseline()
    if not baseline:
        print("No baseline found. Run: python scripts/mypy_baseline.py --update")
        return 1

    regressions = sorted(current - baseline)
    fixed = sorted(baseline - current)

    if fixed and not args.quiet:
        print(f"\n{len(fixed)} baseline error(s) no longer occur (refresh with --update):")
        for entry in fixed[:20]:
            print(f"  - {entry}")
        if len(fixed) > 20:
            print(f"  … and {len(fixed) - 20} more")

    if regressions:
        print(f"\n{len(regressions)} NEW type error(s) introduced:")
        for entry in regressions[:50]:
            print(f"  + {entry}")
        if len(regressions) > 50:
            print(f"  … and {len(regressions) - 50} more")
        return 1

    print(f"\nNo new type errors (baseline: {len(baseline)}, current: {len(current)}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
