apiVersion: v1
kind: Service
metadata:
  name: kubernetes-orchestration
  labels:
    app: kubernetes-orchestration
spec:
  selector:
    app: kubernetes-orchestration
  ports:
    - name: http
      port: 9537
      targetPort: 9537
  type: ClusterIP
