apiVersion: v1
kind: Service
metadata:
  name: security-audit
  labels:
    app: security-audit
spec:
  selector:
    app: security-audit
  ports:
    - name: http
      port: 9551
      targetPort: 9551
  type: ClusterIP
