apiVersion: v1
kind: Service
metadata:
  name: sqlalchemy-security
  labels:
    app: sqlalchemy-security
spec:
  selector:
    app: sqlalchemy-security
  ports:
    - name: http
      port: 9541
      targetPort: 9541
  type: ClusterIP
