apiVersion: v1
kind: Service
metadata:
  name: penetration-testing
  labels:
    app: penetration-testing
spec:
  selector:
    app: penetration-testing
  ports:
    - name: http
      port: 9564
      targetPort: 9564
  type: ClusterIP
