apiVersion: v1
kind: Service
metadata:
  name: datadog-integration
  labels:
    app: datadog-integration
spec:
  selector:
    app: datadog-integration
  ports:
    - name: http
      port: 9533
      targetPort: 9533
  type: ClusterIP
