apiVersion: v1
kind: Service
metadata:
  name: cache-optimization
  labels:
    app: cache-optimization
spec:
  selector:
    app: cache-optimization
  ports:
    - name: http
      port: 9561
      targetPort: 9561
  type: ClusterIP
